#!/bin/bash
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
RED=$(tput setaf 1)
RESET=$(tput sgr0)

RAM_USAGE=$(free | grep Mem | awk '{print $3/$2 * 100.0}')
RAM_USAGE=$(printf "%.0f" $RAM_USAGE)

if [ "$RAM_USAGE" -lt 50 ]; then
  COLOR="$GREEN"
elif [ "$RAM_USAGE" -ge 50 ] && [ "$RAM_USAGE" -lt 75 ]; then
  COLOR="$YELLOW"
else
  COLOR="$RED"
fi

echo -e "${COLOR}$RAM_USAGE%${RESET}"
