#!/bin/bash
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
RED=$(tput setaf 1)
RESET=$(tput sgr0)

GPU_USAGE=$(timeout 2 sudo intel_gpu_top -J | jq '.engines."Render/3D/0".busy')
GPU_USAGE=$(printf "%.0f" $GPU_USAGE)

if [ "$GPU_USAGE" -lt 50 ]; then
  COLOR="$GREEN"
elif [ "$GPU_USAGE" -ge 50 ] && [ "$GPU_USAGE" -lt 75 ]; then
  COLOR="$YELLOW"
else
  COLOR="$RED"
fi

echo -e "${COLOR}$GPU_USAGE%${RESET}"
