vim.keymap.set("v", "<C-c>", "\"+y")

vim.keymap.set("n", "<leader>w", ":w<CR>")
vim.keymap.set("n", "<leader>W", ":wa<CR>")
vim.keymap.set("n", "<leader>q", ":q<CR>")
vim.keymap.set("n", "<leader>Q", ":qa<CR>")
vim.keymap.set("n", "<leader>s", ":%s/")

vim.keymap.set("n", "<M-t>", ":tabnew<CR>")
vim.keymap.set("n", "<M-&>", "1gt")
vim.keymap.set("n", "<M-é>", "2gt")
vim.keymap.set("n", "<M-\">", "3gt")
vim.keymap.set("n", "<M-'>", "4gt")
vim.keymap.set("n", "<M-(>", "5gt")
vim.keymap.set("n", "<M-->", "6gt")
vim.keymap.set("n", "<M-è>", "7gt")
vim.keymap.set("n", "<M-_>", "8gt")
vim.keymap.set("n", "<M-ç>", "9gt")
vim.keymap.set("n", "<M-A>", ":tabmove -1<CR>")
vim.keymap.set("n", "<M-a>", ":tabprev<CR>")
vim.keymap.set("n", "<M-e>", ":tabnext<CR>")
vim.keymap.set("n", "<M-E>", ":tabmove +1<CR>")

vim.keymap.set("n", "<M-$>", ":term<CR>")
vim.keymap.set("n", "<M-h>", ":split<CR>")
vim.keymap.set("n", "<M-v>", ":vsplit<CR>")
vim.keymap.set("n", "<M-z>", "<C-w>k")
vim.keymap.set("n", "<M-Z>", "<C-w>K")
vim.keymap.set("n", "<M-s>", "<C-w>j")
vim.keymap.set("n", "<M-S>", "<C-w>J")
vim.keymap.set("n", "<M-q>", "<C-w>h")
vim.keymap.set("n", "<M-Q>", "<C-w>H")
vim.keymap.set("n", "<M-d>", "<C-w>l")
vim.keymap.set("n", "<M-D>", "<C-w>L")

vim.keymap.set("n", "<leader>i", ":Inspect<CR>")
vim.keymap.set("n", "<leader>,", '/[^\\d0-\\d127]<CR>')

vim.keymap.set("n", "<leader>1", ":e ~/.config/nvim/lua/binds.lua<CR>")
vim.keymap.set("n", "<leader>2", ":e ~/document/github/a-nvim-theme/colors/neon.lua<CR>")
vim.keymap.set("n", "<leader>3", ":e ~/.config/nvim<CR>")
vim.keymap.set("n", "<leader>4", ":e ~/.bash_aliases<CR>")
vim.keymap.set("n", "<leader>5", ":e ~/.bash_env<CR>")
vim.keymap.set("n", "<leader>6", ":e ~/.bashrc<CR>")
vim.keymap.set("n", "<leader>7", ":e ~/document/github/a-setup<CR>")
vim.keymap.set("n", "<leader>8", ":e ~/download<CR>")
vim.keymap.set("n", "<leader>9", ":e ~/.local<CR>")
vim.keymap.set("n", "<leader>0", ":e ~/.<CR>")
vim.keymap.set("n", "<leader>.", ":e ~/.config<CR>")
vim.keymap.set("n", "<leader>/", ":e /<CR>")
vim.keymap.set("n", "<leader>*", ":e#<CR>")
