#!/bin/bash
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
RED=$(tput setaf 1)
RESET=$(tput sgr0)

CPU_USAGE=$(top -bn2 | grep "Cpu(s)" | tail -n 1 | awk '{print $2 + $4}')

if (( $(echo "$CPU_USAGE < 50" |bc -l) )); then
  COLOR="$GREEN"
elif (( $(echo "$CPU_USAGE >= 50 && $CPU_USAGE < 75" |bc -l) )); then
  COLOR="$YELLOW"
else
  COLOR="$RED"
fi

echo -e "${COLOR}$CPU_USAGE%${RESET}"
